title: James M. Smillie # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
degree: BA, Physics - University of Colorado
description: > # your text below (remove <br> elements if you don't need line breaks)
  Background in mathematics, python3, VBA, C++. <a href="about"> See More</a>
  
theme: jekyll-theme-dinky
