title: James M. Smillie # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
degree: BA, Physics - University of Colorado
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="pdf/James McBride Smillie Resume.pdf">> See my Resume</a>
  <br>
  <a href="https://www.linkedin.com/in/james-s-a03574124/">> View my LinkedIn</a>
  <br>
  <a href="/index#software">> Software</a>
  <br>
  <a href="/index#hardware">> Hardware</a>
  
theme: jekyll-theme-dinky
