title: James M. Smillie # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
degree: BA, Physics - University of Colorado
description: > # your text below (remove <br> elements if you don't need line breaks)
  Background in mathematics, python3, VBA, C++. 3+ years experience in ISO accredited quality system management. 1.5+ years working with a start-up tech company as a software and hardware developer.
  
theme: jekyll-theme-dinky
